# .github/workflows/fill-firebase.yml
name: Fill Firebase with Dog Places Data

on:
  # Run once per day
  schedule:
    - cron: '0 8 * * *'  # 8h00 UTC chaque jour

  # Allow manual triggering
  workflow_dispatch:

jobs:
  fill-firebase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Execute Data Collection via Smart Scheduler
      env:
        NODE_ENV: production
        GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
        EXPO_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
        FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
        ENABLE_GOOGLE: true
        ENABLE_OSM: true
        ENABLE_FALLBACK: true
        ENABLE_VALIDATION: true
        GOOGLE_DAILY_QUOTA: 2000
        LOG_LEVEL: info
        NOTIFY_ON_FAILURE: true
      run: |
        echo "🚀 Starting intelligent data collection..."
        node scripts/scheduleManager.js execute dogPlaces
        sleep 30
        node scripts/scheduleManager.js execute addresses